### ISSUE TITLE
COLL issue. 

### ISSUE THREAD

**Issue by aclaiman** [RafaelSubia/JRSV_Presets#2]
Hi!
No coll saving with cyclone 0.3
![coll_issue](https://user-images.githubusercontent.com/37425769/59034153-cd96b000-8840-11e9-83ce-d1415a5eb0f1.png)

**Comment by JRSV** [comment]
if I recall correctly, its because the file does not exist, but once you save a preset it should work. I have abandoned the call object altogether in the latest version (not public yet) as now I use the param object. anyway, let me know if it works by ignoring that message. Just save a preset and check if it creates the file.

**Comment by aclaiman** [comment]
Thanks for your answer!
The  file is created but it is empty as you can see in the picture. (asd-presets.txt)
the console gives: coll: can't find file 'C:/pd64bits/projects/asd-presets.txt'

**Comment by JRSV** [comment]
are there any missing objects when loading? it looks like you may have cleared your screen for that screenshot. The preset manager says no preset, but there is a connection failed message. maybe a dependency missing?

**Comment by aclaiman** [comment]
I don't think so, but I going to check that out and get back to you.
Thanks!
Regards from Argentina.
Andres

**Comment by JRSV** [comment]
Hola Andres,
pudiste probar lo que te pedi?

**Comment by JRSV** [comment]
Closing this as there is no response
