### ISSUE TITLE
RSVP not functioning due to "couldn't create initbang"

### ISSUE THREAD

**Issue by Utilities78** [RafaelSubia/JRSV_Presets#3]
Hi,
Trying out rsvp on PD 0.52.2. Its not generating the GUIs when I click on them. I've declared the following libraries- 
  - HCS
  - iemguts
  - iemlib
  - flatgui
  - cyclone
  - tof
  - zexy

I'm getting the "initbang....couldn't create" message in the console. 

![Screenshot 2022-11-01 at 12 57 45](https://user-images.githubusercontent.com/104306213/199238938-a6f2600c-5b85-47c4-beea-a488775989e1.png)

I've opened both GUI-creator and PresetManager and I can see on both that initbang is not recognised
![Screenshot 2022-11-01 at 13 05 24](https://user-images.githubusercontent.com/104306213/199239766-7be41143-4e7d-4c14-8a37-d0fc6d94fc4a.png)

Will rsvp still function if I alter these to loadbang do you think? Or is there another library I can download?

Many thanks

**Comment by Utilities78** [comment]
Should have mentioned this is on a MacBook running Big Sur 11.6.1

**Comment by Utilities78** [comment]
Ok by changing initbang to loadbang I am getting my GUI objects. And by changing some of the declarations from stdlib to lib I am losing error messages. However nothing is being written to the text files when I save a preset and PD won't open my saved patch when I close and reopen. Could this be due to using loadbang instead of initbang?

**Comment by JRSV** [comment]
So, [initbang] is necesarry because it will trigger when a new abstraction GUI is created, [loadbang] will only work when patch is loaded. Are you getting any other errors? you have all other warnings? [initbang] is part of iemguts library. (this object was created and moved around by various developers) the [iemguts] version seems to be the best now. Can you try it with the proper external and let me know how that goes? also, this is a version that needs all these externals, there is a PD vanilla compatible version here: [full vanilla](https://github.com/JRSV/RSVP.V3.full-vanilla)

**Comment by Utilities78** [comment]
Thanks for the quick response!I'll check my externals paths and declarations. See if I can get it working with initbang.Will let you know the outcome.Cheers!On 01/11/2022, 14:02 Jose Rafael Subia Valdez ***@***.***> wrote:

   
  So, [initbang] is necesarry because it will trigger when a new abstraction GUI is created, [loadbang] will only work when patch is loaded. Are you getting any other errors? you have all other warnings? [initbang] is part of iemguts library. (this object was created and moved around by various developers) the [iemguts] version seems to be the best now.

**Comment by JRSV** [comment]
Strongly recommend the new version in the link. It is an improved version and I still maintain it

**Comment by Utilities78** [comment]
Ah didn't realise there was a V3. Thank you. All sorted now
